### ISSUE TITLE
I’m having some trouble with automatic sync.

### ISSUE THREAD

**Issue by Mo-Shakib** [leetnotion/vscode-leetnotion#2]
I recently solved a problem and submitted it using the extension. However, the changes didn’t show up in the template. I had to manually update the template using the `submission.json` file. Is there a way to make this automatic?

**Comment by codewithsathya** [comment]
It is automatic and it should work.
![CleanShot 2024-10-30 at 18 22 20@2x](https://github.com/user-attachments/assets/3fe94e6e-5861-492a-a95a-05ee7e74c4db)

Are you getting something similar to this after you submit?

**Comment by Mo-Shakib** [comment]
No, I get this:
![Screenshot 2024-10-31 at 2 45 18 AM](https://github.com/user-attachments/assets/ed2bc237-a837-4ff2-a271-862e0455af19)

How do I enable that?

**Comment by codewithsathya** [comment]
It seems you missed the notion integration. Run "Integrate notion with the leetnotion extension" command again.

**Comment by Mo-Shakib** [comment]
I have done that, even I cleared all data and tried that still not working. I think `Custom Notion Properties` is not working, or do I need to change anything in the Notion Integration?

**Comment by Mo-Shakib** [comment]
As you can see, updating problems works without any error, so I believe there is no problem in the Integration with Notion.
But the `Custom Notion Properties` is not showing up, is there any way to manually set it?

![Screenshot 2024-10-31 at 10 48 43 AM](https://github.com/user-attachments/assets/45ca83f3-e389-471f-a1d6-f467963afbb8)

**Comment by codewithsathya** [comment]
Can you please send a screenshot of output when you submit any question like below
![CleanShot 2024-10-31 at 13 17 23@2x](https://github.com/user-attachments/assets/7be873db-49d0-4789-a6bf-63bce6cd2565)

**Comment by Mo-Shakib** [comment]
![Screenshot 2024-10-31 at 4 54 36 PM](https://github.com/user-attachments/assets/1c58e886-620a-467f-a330-5e146bc8b3eb)

**Comment by Mo-Shakib** [comment]
![Screenshot 2024-10-31 at 5 01 59 PM](https://github.com/user-attachments/assets/82fe6825-b3ed-43f4-881a-bf14cbaffaeb)

**Comment by codewithsathya** [comment]
Did you change the notion properties in the template? Once try clearing all data, uninstall the extension, install extension again and setup again.

**Comment by Mo-Shakib** [comment]
I did not change the notion properties in the template. Tried in VS code insider with a fresh install of everything, nothing helps!  :(

![Screenshot 2024-11-02 at 1 56 06 AM](https://github.com/user-attachments/assets/39b99ada-7254-4f7b-b721-724373984265)

**Comment by Mo-Shakib** [comment]
This it my setting:
```{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Bearded Theme Vivid Black",
    "leetnotion.addCodeToSubmissionPage":true,
    "leetnotion.defaultLanguage": "python3",
    "leetnotion.editor.shortcuts": [
        "submit",
        "test",
        "description",
        "solution"
    ],
    "leetnotion.showDescription": "Both",
    "leetnotion.workspaceFolder": "/Users/shakib/Projects/LeetCode",
    "leetnotion.language.header": {

    },
    "leetnotion.enableNotionIntegration": true,
    "leetnotion.filePath": {
     "default": {
      "folder": "${difficulty}",
      "filename": "${id}-${kebab-case-name}.${ext}"
    },
        "python3": {
        "folder": "${difficulty}",
        "filename": "${id}-${kebab-case-name}.${ext}"
    }
    },
    "leetnotion.hint.commentDescription": false,
    "leetnotion.hint.commandShortcut": false,
    "leetnotion.hint.configWebviewMarkdown": false,
    "leetnotion.hint.setDefaultLanguage": false
}```
